#!/usr/bin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	need dbus
}

start() {
	ebegin "Starting elogind"

	start-stop-daemon --start --quiet \
		--pidfile /run/elogind.pid \
		--exec /usr/lib/elogind/elogind -- --daemon
	eend $?
}

stop() {
	ebegin "Stopping elogind"
	start-stop-daemon --stop --quiet --pidfile "${ELOGIND_PIDFILE}"
	eend $?
}
